services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - app
    ports:
      - 8080:8080
  recipe-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - adminer
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules
  seed:
    profiles: ["seed"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: app
      NODE_ENV: development
      DB_LOGGING: True
    command: [sh, -c, 'npm run seed']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app:

volumes:
  postgres_data: